services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: burgundy
  server:
    build:
      context: ./
      target: dev
    depends_on:
      - db
    volumes:
      - ./:/app/
      - /app/node_modules/
      - /app/server/node_modules/
      - /app/assets/node_modules/
    ports: 
      - 3000:3000
      