services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  server:
    build:
      context: ./
      target: dev
    volumes:
      - ./server:/app/server
      - /app/server/node_modules/
    ports: 
      - 3000:3000