services:
  db:
    image: mongo:5
    restart: always
    volumes:
      - ./.db:/data/db
  server:
    build:
      context: ./
      target: dev
    depends_on:
      - db
    volumes:
      - ./:/app/
      - /app/node_modules/
      - /app/server/node_modules/
      - /app/assets/node_modules/
    ports: 
      - 3000:3000
      