DROP TABLE IF EXISTS view_cells;
DROP TABLE IF EXISTS views;
DROP TABLE IF EXISTS i18n;
DROP TABLE IF EXISTS files;
DROP EVENT IF EXISTS expire_pwd_resets;
DROP TABLE IF EXISTS pwd_resets;
DROP TABLE IF EXISTS registrants;
DROP TABLE IF EXISTS users;
