name: burgundy
services:
  mongo:
    image: mongo:6
    ports:
      - 27017:27017 
    restart: always
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
    command: mongod --replSet rs0
    healthcheck:
      test: test $$(mongosh --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"localhost:27017\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 10s